import { NAVBAR_HEIGHT } from '@/lib/constants'
import React from 'react'
import Navbar from '@/components/ui/Navbar'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import  Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Home | mReport</title>
        <meta name="description" content="Live report mapping platform" />
        <link rel="icon" href="/mreport.png" />
      </head>
     
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className='h-full w-full '>
            <Navbar />
            <main className={`h-full flex w-full flex-col `} style={{ paddingTop: `${NAVBAR_HEIGHT}px` }}>
                {children}
            </main>
        </div>
        </Providers>
      </body>
    </html>
  );
}
